# Generated by Django 4.2.16 on 2024-09-28 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_featurelist_remove_room_room_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mainapp.room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='mainapp.featurelist'),
        ),
    ]
