# Generated by Django 4.2.16 on 2024-09-28 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_rename_features_room_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='services',
        ),
        migrations.AddField(
            model_name='room',
            name='features',
            field=models.ManyToManyField(to='mainapp.featurelist'),
        ),
    ]
