# Generated by Django 3.2 on 2024-09-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20240928_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='available_room',
        ),
        migrations.AlterField(
            model_name='room',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
