# Generated by Django 3.2 on 2024-09-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20240928_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='adults',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='arrival_time',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='room_quanity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='special_request',
            field=models.TextField(blank=True, null=True),
        ),
    ]
