# Generated by Django 3.2 on 2024-09-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20240929_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='payment',
            field=models.BooleanField(default=False),
        ),
    ]
