# Generated by Django 3.2 on 2024-09-29 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_reservation_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='room_quanity',
            new_name='room_quantity',
        ),
    ]
