# Generated by Django 3.2 on 2024-09-30 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_auto_20240930_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prebrookingId', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('expiration_time', models.DateTimeField()),
            ],
        ),
    ]
