# Generated by Django 3.2 on 2024-09-30 13:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_prebooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='prebooking',
            name='adults',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prebooking',
            name='check_in_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prebooking',
            name='check_out_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prebooking',
            name='room_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.room'),
        ),
        migrations.AddField(
            model_name='prebooking',
            name='room_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prebooking',
            name='prebrookingId',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
