# Generated by Django 3.2 on 2024-10-01 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_auto_20240930_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='hold_until',
        ),
        migrations.RemoveField(
            model_name='room',
            name='is_on_hold',
        ),
        migrations.AddField(
            model_name='prebooking',
            name='hold_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prebooking',
            name='is_on_hold',
            field=models.BooleanField(default=False),
        ),
    ]
