# Generated by Django 3.2 on 2024-10-02 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_reservation_confirmation_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='confirmation_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
