# Generated by Django 3.2 on 2024-10-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_alter_reservation_confirmation_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_check_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='is_check_out',
            field=models.BooleanField(default=False),
        ),
    ]
