# Generated by Django 3.2 on 2024-10-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_auto_20241002_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='booked_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
