# Generated by Django 3.2 on 2024-10-09 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_alter_reservation_booked_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='reference_objects/')),
                ('size', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FootMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foot_image', models.ImageField(upload_to='foot_images/')),
                ('size', models.FloatField(blank=True, null=True)),
                ('reference_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.referenceobject')),
            ],
        ),
    ]
