# Generated by Django 3.2 on 2024-10-10 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_footmeasurement_referenceobject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footmeasurement',
            name='reference_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.referenceobject'),
        ),
    ]
