# Generated by Django 3.2 on 2024-10-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_alter_footmeasurement_reference_object'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('length', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='referenceobject',
            name='image',
        ),
        migrations.RemoveField(
            model_name='referenceobject',
            name='size',
        ),
        migrations.AddField(
            model_name='referenceobject',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='referenceobject',
            name='width_cm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='FootMeasurement',
        ),
    ]
