# Generated by Django 3.2 on 2024-10-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0024_customeuser_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisplaySlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('slider_image', models.ImageField(default='0.jpeg', upload_to='Slider')),
                ('button_name', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
