# Generated by Django 3.2 on 2024-10-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0025_displayslider'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
